# Autogenerated wrapper script for SDL12_compat_jll for aarch64-apple-darwin
export libSDL

using SDL2_jll
JLLWrappers.@generate_wrapper_header("SDL12_compat")
JLLWrappers.@declare_library_product(libSDL, "@rpath/libSDL-1.2.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll)
    JLLWrappers.@init_library_product(
        libSDL,
        "lib/libSDL.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
