# Autogenerated wrapper script for SDL12_compat_jll for x86_64-linux-musl
export libSDL

using SDL2_jll
JLLWrappers.@generate_wrapper_header("SDL12_compat")
JLLWrappers.@declare_library_product(libSDL, "libSDL-1.2.so.0")
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll)
    JLLWrappers.@init_library_product(
        libSDL,
        "lib/libSDL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
